language: python

install:
  - pip install tox
  - pip install coveralls
  #- pip install python-coveralls

script:
  - tox

env:
  - TOXENV=py27-django12
  - TOXENV=py27-django13
  - TOXENV=py27-django14
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py33-django16
  - TOXENV=py27-django17
  - TOXENV=py33-django17
  - TOXENV=py34-django17
  - TOXENV=pypy-django16
  - TOXENV=pypy-django17

after_success:
  - coveralls